package page;

public enum Constants {

    BUTTON_PLAY,
    BUTTON_PLAYSELECTION,
    BUTTON_LOOP,
    BUTTON_STOP,

    FIELD_PLAYSTART,
    FIELD_LOOPSTART,
    FIELD_LOOPSTOP,
    FIELD_BPM,

    MENU_FILE_NEW,
    MENU_FILE_OPEN,
    MENU_FILE_SAVE,
    MENU_FILE_SAVEAS,
    MENU_FILE_CLOSE,
    MENU_FILE_QUIT,

    MENU_EDIT_UNDO,
    MENU_EDIT_REDO,
    MENU_EDIT_CUT,
    MENU_EDIT_COPY,
    MENU_EDIT_PASTE,
    MENU_EDIT_CLEAR,
    MENU_EDIT_SELECTALL,
    MENU_EDIT_INSERTBARS,
    MENU_EDIT_REMOVEBARS,

    MENU_TRACK_ADD,
    MENU_TRACK_REMOVE,

    MENU_VIEW_SETTHEME,

    MENU_MUSIC_PLAY,
    MENU_MUSIC_PLAYSELECTION,
    MENU_MUSIC_STOP,
    MENU_MUSIC_FIND,
    MENU_MUSIC_SOUNDFONT,
    ;

    @Override
    public String toString() {
        return this.name();
    }

}
